### ISSUE TITLE
Converts subtitles and drops other streams

### ISSUE THREAD

**Issue by bdaroz** [suntong/ffcvt#2] opened 2016-06-20 06:02 UTC
So I have a file I tested with your script, the `ffprobe` dump below (some metadata pulled and file name scrubbed):

```
Input #0, matroska,webm, from 'file.mkv':
  Metadata:
    encoder         : libebml v1.3.0 + libmatroska v1.4.1
    creation_time   : 2014-07-28 16:46:41
    Stream #0:0(eng): Video: h264 (High), yuv420p(tv, bt709), 1912x1072 [SAR 1:1 DAR 239:134], 23.98 fps, 23.98 tbr, 1k tbn, 2k tbc (default)
    Stream #0:1(eng): Audio: ac3, 48000 Hz, 5.1(side), fltp, 384 kb/s (default)
    Stream #0:2(eng): Subtitle: subrip
    Stream #0:3: Video: mjpeg, yuvj444p(pc, bt470bg/unknown/unknown), 120x176, 90k tbr, 90k tbn, 90k tbc
    Metadata:
      filename        : small_cover.jpg
      mimetype        : image/jpeg
    Stream #0:4: Video: mjpeg, yuvj444p(pc, bt470bg/unknown/unknown), 600x882, 90k tbr, 90k tbn, 90k tbc
    Metadata:
      filename        : cover.jpg
      mimetype        : image/jpeg
    Stream #0:5: Video: mjpeg, yuvj444p(pc, bt470bg/unknown/unknown), 1067x600, 90k tbr, 90k tbn, 90k tbc
    Metadata:
      filename        : cover_land.jpg
      mimetype        : image/jpeg
    Stream #0:6: Video: mjpeg, yuvj444p(pc, bt470bg/unknown/unknown), 213x120, 90k tbr, 90k tbn, 90k tbc
    Metadata:
      filename        : small_cover_land.jpg
      mimetype        : image/jpeg
```

However, running your script as `ffcvt -f file.mkv -ac -crf 20 -debug 1` as not to reencode the audio track (which would need to be transcoded again to be played back on some of my devices) gives this resulting `ffprobe` dump:

```
Input #0, matroska,webm, from 'file_.mkv':
  Metadata:
    ENCODER         : Lavf56.36.100
    Stream #0:0(eng): Video: hevc (Main), yuv420p(tv), 1912x1072 [SAR 1:1 DAR 239:134], 23.98 fps, 23.98 tbr, 1k tbn, 23.98 tbc (default)
    Stream #0:1(eng): Audio: ac3, 48000 Hz, 5.1(side), fltp, 384 kb/s (default)
    Stream #0:2(eng): Subtitle: ass
```

Note the subtitles have been converted from `subrip` to `ass`, and the other 4 streams are missing completely.

The conversion should be doing neither, ideally, or at the very least, shouldn't be doing so silently.

**Comment by suntong** [comment] 2016-06-20 12:50
Hmm... I've never dealt with videos of 4 streams before. 
What's the actual `ffmpeg` command that `ffcvt` invoked? It'd be in the `-debug 1` output.

**Comment by bdaroz** [comment] 2016-06-20 21:18
I don't have the debug log with me at the moment, but I do remember looking at it after I posted the issue. The problem is that it just adds `-c:v libx265 -c:a copy` (and I don't recall what the `-c:s` parameter was), but there was no stream mapping (`-map`) so those parameters would only affect the first stream found of each type.

I didn't test but my experience w/ ffmpeg would tell me it's likely anything with multiple audio or subtitle streams would also be affected (eg, regular and SDH subs, or DTS 'show' w/ FLAC commentary audio). If you'd really like the `-debug 1` log I can try it again later.

**Comment by suntong** [comment] 2016-06-21 01:29
That's OK. I don't need the `-debug 1` log any more, because I've already known what's happening. 

I have to close this because ffcvt was designed to be a fan-level product, not anywhere close to commercial-grade software. Even if you are willing to send in patches on this, I'd hesitate to take them, as it would complicate the code base without benefiting 99% of normal case/people, at least before I can come up with some plug-in mechanism to allow such contribution. 

Good luck with your endeavor. All the best.

**Closed** 2016-06-21 01:29 UTC

**Comment by suntong** [comment] 2023-05-17 03:37
Fixed in 

- https://github.com/suntong/ffcvt/issues/9
- https://github.com/suntong/ffcvt/issues/12
